# Generated Python code from HTML
def generate_html():
    """Function that returns the HTML content"""
    from html import escape

    return """\
<!DOCTYPE html>\n"
        "<html lang=\"fr\">\n"
        "<head>\n"
        "  <meta charset=\"utf-8\">\n"
        "  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n"
        "  <title>Tynorah — Sign In</title>\n"
        "  <link rel=\"stylesheet\" href=\"style.css\">\n"
        "  <style>\n"
        "    body {\n"
        "      margin: 0;\n"
        "      height: 100vh;\n"
        "      background: #f5f5f5;\n"
        "      position: relative;\n"
        "    }\n"
        "    .container {\n"
        "      width: 450px;\n"
        "      max-width: 92vw;\n"
        "      background: #fff;\n"
        "      border-radius: 60px;\n"
        "      box-shadow: 0 6px 18px rgba(0,0,0,0.1);\n"
        "      position: absolute; /* nécessaire pour JS */\n"
        "      padding: 20px;\n"
        "    }\n"
        "  </style>\n"
        "</head>\n"
        "<body>\n"
        "\n"
        "<div class=\"container\">\n"
        "  <header class=\"header\">\n"
        "    <div class=\"brand\">TYNORAH</div>\n"
        "    <h1>LOGIN</h1>\n"
        "    <p class=\"subtitle\">Enter your details to access your account</p>\n"
        "  </header>\n"
        "\n"
        "  <form id=\"login-form\" class=\"content\" action=\"#\" method=\"POST\">\n"
        "    <label for=\"login-email\">Email</label>\n"
        "    <input id=\"login-email\" name=\"email\" type=\"email\" autocomplete=\"username\" placeholder=\"example@email.com\" required>\n"
        "\n"
        "    <div style=\"display: flex; justify-content: space-between; align-items: flex-end;\">\n"
        "      <label for=\"login-password\">Password</label>\n"
        "      <a href=\"forgot-password.html\" class=\"signin-link\" style=\"font-size: 11px;\">Forgot password?</a>\n"
        "    </div>\n"
        "    <input id=\"login-password\" name=\"password\" type=\"password\" autocomplete=\"current-password\" placeholder=\"•••••••••••••\" required>\n"
        "\n"
        "    <div class=\"terms\">\n"
        "      <input id=\"remember\" type=\"checkbox\">\n"
        "      <label for=\"remember\" class=\"terms-label\">Remember me</label>\n"
        "    </div>\n"
        "\n"
        "    <button class=\"btn\" type=\"submit\" style=\"margin-top: 30px;\">SIGN IN</button>\n"
        "\n"
        "    <p class=\"small\">\n"
        "      Don\'t have an account? <a href=\"signup.html\" class=\"signin-link\">Sign up</a>\n"
        "    </p>\n"
        "  </form>\n"
        "</div>\n"
        "\n"
        "<script>\n"
        "  // Fonction pour centrer le container\n"
        "  function centerContainer() {\n"
        "    const container = document.querySelector(\'.container\');\n"
        "    const winWidth = window.innerWidth;\n"
        "    const winHeight = window.innerHeight;\n"
        "    const contWidth = container.offsetWidth;\n"
        "    const contHeight = container.offsetHeight;\n"
        "\n"
        "    const left = (winWidth - contWidth) / 2;\n"
        "    const top = (winHeight - contHeight) / 2;\n"
        "\n"
        "    container.style.left = left + \'px\';\n"
        "    container.style.top = top + \'px\';\n"
        "  }\n"
        "\n"
        "  window.addEventListener(\'load\', centerContainer);\n"
        "  window.addEventListener(\'resize\', centerContainer);\n"
        "\n"
        "  // Gestion du formulaire\n"
        "  document.getElementById(\'login-form\').addEventListener(\'submit\', function(e) {\n"
        "    e.preventDefault(); // empêche l\'envoi réel\n"
        "\n"
        "    const email = document.getElementById(\'login-email\').value.trim();\n"
        "    const password = document.getElementById(\'login-password\').value.trim();\n"
        "\n"
        "    // Exemple simple de validation (à remplacer par une vraie vérification côté serveur)\n"
        "    if (email !== \"\" && password !== \"\") {\n"
        "      // Redirection vers feed.html si \"authentification\" réussie\n"
        "      window.location.href = \"feed.html\";\n"
        "    } else {\n"
        "      alert(\"Veuillez entrer vos identifiants.\");\n"
        "    }\n"
        "  });\n"
        "</script>\n"
        "\n"
        "</body>\n"
        "</html>"""

if __name__ == "__main__":
    html = generate_html()
    print(html)
    # You can also write to a file:
    # with open("output.html", "w") as f:
    #     f.write(html)
